server:
  port: 0

spring:
  application:
    name: uniquone-user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/uniquOne_user?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce

logging:
  level:
    com.sparos.uniquone.msauserservice: DEBUG

#86400000 하루
#secret 마음에 드는 이름 사용하면됨.
#토큰 생성 시간
token:
  expiration_time: 86400000
  secret: user_token